version: '3.8'

services:
  redis1:
    image: redis:latest
    container_name: redis1
    ports:
      - "6379:6379"

  redis2:
    image: redis:latest
    container_name: redis2
    ports:
      - "6380:6379"

  redis3:
    image: redis:latest
    container_name: redis3
    ports:
      - "6381:6379"

  redis4:
    image: redis:latest
    container_name: redis4
    ports:
      - "6382:6379"

  redis5:
    image: redis:latest
    container_name: redis5
    ports:
      - "6383:6379"